name: Build Containers and Publish to GHCR (On Release)

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - atspm-webui
          - atspm-config-api
          - atspm-data-api
          - atspm-identity-api
          - atspm-report-api
          - atspm-watchdog
          - atspm-eventlogutil

    steps:
      - name: â¬‡ï¸ Set up code
        uses: actions/checkout@v4

      - name: ðŸ“ Get Working Dir
        run: |
          docker_dir="$(cat .github/filters.json | jq '."${{matrix.name}}"' | tr -d '**\n"')"
          echo DOCKERFILE_DIR=${docker_dir} >> $GITHUB_ENV

      - name: ðŸ³ Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: ðŸ—ï¸ Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ·ï¸ Set tags for GHCR
        id: meta
        run: |
          IMAGE_REPO="ghcr.io/${{ github.repository }}/${{ matrix.name }}"
          echo "IMAGE_TAGS=${IMAGE_REPO}:${GITHUB_REF#refs/tags/},${IMAGE_REPO}:latest" >> $GITHUB_ENV

      - name: ðŸ“¦ Build and push image (non-WebUI)
        uses: docker/build-push-action@v6
        if: ${{ matrix.name != 'atspm-webui'}}
        with:
          builder: ${{ steps.builder.outputs.name }}
          tags: ${{ env.IMAGE_TAGS }}
          context: Atspm/
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.description=${{ github.event.release.body }}

      - name: ðŸ“¦ Build and push image WebUI
        uses: docker/build-push-action@v6
        if: ${{ matrix.name == 'atspm-webui'}}
        with:
          builder: ${{ steps.builder.outputs.name }}
          tags: ${{ env.IMAGE_TAGS }}
          context: ${{ env.DOCKERFILE_DIR }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.description=${{ github.event.release.body }}
