name: Build, Publish, and Attach Docker Images to Release

on:
  release:
    types: [published, prereleased]

permissions:
  id-token: write
  contents: write  # Needed to upload assets to GitHub release

jobs:
  changes:
    name: Find Containers to Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: .github/filters.json
    outputs:
      changes: ${{ steps.changes.outputs.changes }}

  build:
    name: Build and Publish Docker Images
    needs: changes
    if: ${{ needs.changes.outputs.changes != '[]'}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJson(needs.changes.outputs.changes) }}

    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ“ Get Working Dir
        run: |
          docker_dir="$(cat .github/filters.json | jq '."${{ matrix.name }}"' | tr -d '**\n"')"
          echo "DOCKERFILE_DIR=${docker_dir}" >> $GITHUB_ENV

      - name: ğŸ·ï¸ Extract Release Tag
        id: meta
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: ğŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ”‘ Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ“¦ Build and Push Docker Image
        uses: docker/build-push-action@v6
        if: ${{ matrix.name != 'atspmwebsite' }}
        with:
          context: Atspm/
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.VERSION }}
          push: true

      - name: ğŸ“¦ Build and Push Docker Image for WebUI
        uses: docker/build-push-action@v6
        if: ${{ matrix.name == 'atspmwebsite' }}
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.VERSION }}
          push: true

      - name: ğŸ“ List Docker Images
        run: docker images

      - name: ğŸ’¾ Save Docker Image as Tar File
        run: |
          docker save ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.VERSION }} -o ${{ matrix.name }}.tar

      - name: ğŸ“¦ Tag and Push Image to GHCR
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.VERSION }} ghcr.io/opensourcetransportation/${{ matrix.name }}:${{ env.VERSION }}
          docker push ghcr.io/opensourcetransportation/${{ matrix.name }}:${{ env.VERSION }}

      - name: ğŸ“¤ Upload Docker Image to GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: ${{ matrix.name }}.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
